### ISSUE TITLE
WP-Rocket and Pressbooks-Book cause error message 

### ISSUE THREAD

**Issue by saschafoerster** [pressbooks/pressbooks-book#390]
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

Everything seems to work, just I get every two minutes this error message:

```
PHP Fatal error:  Uncaught Error: Call to undefined function WP_Rocket\Subscriber\Preload\get_current_screen() in /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/classes/subscriber/preload/class-preload-subscriber.php:187
Stack trace:
#0 /var/www/html/wordpress/wp-includes/class-wp-hook.php(286): WP_Rocket\Subscriber\Preload\Preload_Subscriber->notice_preload_triggered('')
#1 /var/www/html/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/html/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/html/wordpress/wp-content/themes/pressbooks-book/functions.php(32): do_action('admin_notices')
#4 /var/www/html/wordpress/wp-settings.php(426): include('/var/www/html/w...')
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1188): require('/var/www/html/w...')
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1111): WP_CLI\Runner->load_wordpress()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/La in /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/classes/subscriber/preload/class-preload-subscriber.php on line 187
Fatal error: Uncaught Error: Call to undefined function WP_Rocket\Subscriber\Preload\get_current_screen() in /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/classes/subscriber/preload/class-preload-subscriber.php:187
Stack trace:
#0 /var/www/html/wordpress/wp-includes/class-wp-hook.php(286): WP_Rocket\Subscriber\Preload\Preload_Subscriber->notice_preload_triggered('')
#1 /var/www/html/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/html/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/html/wordpress/wp-content/themes/pressbooks-book/functions.php(32): do_action('admin_notices')
#4 /var/www/html/wordpress/wp-settings.php(426): include('/var/www/html/w...')
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1188): require('/var/www/html/w...')
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1111): WP_CLI\Runner->load_wordpress()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/La in /var/www/html/wordpress/wp-content/plugins/wp-rocket/inc/classes/subscriber/preload/class-preload-subscriber.php on line 187
```

### Steps to Reproduce

1. Install WordPress Multisite MultiNetwork
2. Install PressBooks with all Pressbooks Book
3. Install WP-Rocket

**Comment by greatislander** [comment]
Thanks for reporting.

**Comment by saschafoerster** [comment]
Seems to be away by itself... thanks anyway! :)
